version: '3.9'
services:

  rated-movie-info-service:
    container_name: rated-movie-info-container
    image: rated-movie-info-image
    ports:
      - 8081:8081
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"

  movie-info-service:
    container_name: movie-info-container
    image: movie-info-image
    ports:
      - 8082:8082

  movie-rating-service:
    container_name: movie-rating-container
    image: movie-rating-image
    ports:
      - 8083:8083
